### ISSUE TITLE
Brak herbu miasta Bielawa 

### ISSUE THREAD

**Issue by G4naD** [Deykun/maps#11]
Na mapie, jak i w bazie brakuje herbu miasta Bielawa.

**Comment by Deykun** [comment]
### Before
![obraz](https://github.com/user-attachments/assets/59a0dfc1-f5eb-4c6e-81d4-9b0b53be51de)

### After
![obraz](https://github.com/user-attachments/assets/1e003a5b-51b0-4af7-99a3-17f66f3f565f)

![obraz](https://github.com/user-attachments/assets/0f0ebdd3-0f21-414b-b70d-1f912f073431)
