### ISSUE TITLE
Coat of arms of Katowice - missing tag "hammer"

### ISSUE THREAD

**Issue by MacQtosh** [Deykun/maps#51]
The coat of arms of Katowice contains a trip hammer, but in the filters when selecting "hammer" the coat of arms of Katowice is missing.

**Comment by Deykun** [comment]
Fixed in https://github.com/Deykun/maps/commit/3387ef92734eec368eba03d7e65bc44548892e74

![obraz](https://github.com/user-attachments/assets/f9e50a0a-7e44-45db-943f-a0c36f544a8b)
