### ISSUE TITLE
Złe dopasowanie herbu Jastrzębie-Zdrój

### ISSUE THREAD

**Issue by Zeeboo-pl** [Deykun/maps#53]
Powinien być dodany filtr: młot (i ewentualnie kilof)
Wg wiki: 
Herb przedstawia na zielonej tarczy czarnego jastrzębia z rozpostartymi skrzydłami, przysiadającego na białych insygniach górniczych (według innej wersji jastrząb unosi się i trzyma te insygnia w swych łapach). Na korpusie jastrzębia widnieje biała kropla. 

-  insygnia górnicze : potocznie górnicze **młotki** (składa się z dwóch skrzyżowanych narzędzi: [żelazka](https://pl.wikipedia.org/wiki/%C5%BBelazko_(g%C3%B3rnictwo)) i [pyrlika](https://pl.wikipedia.org/wiki/Pyrlik))

**Comment by Deykun** [comment]
### After
![obraz](https://github.com/user-attachments/assets/343ce099-a2bb-4498-9a00-0d4cc67a8402)
